apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: example-voting-app

spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379