apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: example-voting-app
spec:
  type: NodePort
  
  selector:
    name: voting-app-pod
    app: example-voting-app

  ports:
  - port: 80
    targetPort: 80
