apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: example-voting-app
spec:
  selector:
    name: redis-pod
    app: example-voting-app
  ports:
  - port: 6379
    targetPort: 6379
