apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: example-voting-app
spec:
  type: NodePort
  selector:
    name: result-app-pod
    app: example-voting-app

  ports:
  - port: 80
    targetPort: 80
