apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mysql
  name: wordpress-mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql
status:
  loadBalancer: {}
