apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: wordpress
  name: wordpress
spec:
  ports:
  - port: 80
    nodePort: 31004
  selector:
    name: wordpress
  type: NodePort
status:
  loadBalancer: {}
